name: Build on new act_runner release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.get-release.outputs.latest }}
      current: ${{ steps.get-current.outputs.current }}
      changed: ${{ steps.compare.outputs.changed }}
    steps:
      - uses: actions/checkout@v4

      - id: get-release
        run: |
          latest=$(curl -s https://gitea.com/api/v1/repos/gitea/act_runner/releases | jq -r '.[0].tag_name')
          echo "latest=${latest#v}" >> $GITHUB_OUTPUT

      - id: get-current
        run: |
          current=$(grep '^ARG ACT_RUNNER_VERSION=' Dockerfile | cut -d= -f2)
          echo "current=$current" >> $GITHUB_OUTPUT

      - id: compare
        run: |
          if [ "${{ steps.get-release.outputs.latest }}" = "${{ steps.get-current.outputs.current }}" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-release
    if: needs.check-release.outputs.changed == 'true'
    runs-on: ubuntu-latest
    environment: build

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Update Dockerfile version
        run: |
          sed -i "s/ACT_RUNNER_VERSION=.*/ACT_RUNNER_VERSION=${{ needs.check-release.outputs.latest }}/" Dockerfile

      - name: Commit updated Dockerfile
        env:
          TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://lanakod:${TOKEN}@github.com/lanakod/gitea_act_runner.git
          git add Dockerfile
          git commit -m "Update act_runner to version ${{ needs.check-release.outputs.latest }}" || echo "No changes to commit"
          git push

      - name: Build image
        run: |
          VERSION=${{ needs.check-release.outputs.latest }}

          docker build \
            --build-arg ACT_RUNNER_VERSION=$VERSION \
            -t ghcr.io/lanakod/gitea_act_runner:$VERSION \
            -t ghcr.io/lanakod/gitea_act_runner:latest \
            .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.check-release.outputs.latest }}
          name: "act_runner ${{ needs.check-release.outputs.latest }}"
          body: "Automated release for act_runner version ${{ needs.check-release.outputs.latest }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
